<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <VersionPrefix>1.0.6</VersionPrefix>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>C# implementation of the ElectronBot SDK, providing USB data read/write functionality for host computer development.</Description>
    <PackageIcon>package-icon.png</PackageIcon>
    <Title>ElectronBot WinUsb SDK</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".\package-icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibUsbDotNet" Version="3.0.156-alpha-g43700ffc41">
      <Aliases></Aliases>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElectronBot.DotNet\ElectronBot.DotNet.csproj" />
  </ItemGroup>

</Project>
